### ISSUE TITLE
pls keeps returing 'ul'

### ISSUE THREAD

**Issue by DarrCoh** [MxDkl/pls#1]
Hello,

I'm experiencing an issue with the following terminal output, where nothing seems to happen. 

Please let me know if you require any additional details.

_pls_ is a great idea btw !

<img width="1486" alt="CleanShot 2023-03-13 at 02 46 01@2x" src="https://user-images.githubusercontent.com/60644530/224589992-1b760228-8001-4e85-b5ab-86000d3fe9c8.png">

**Comment by MxDkl** [comment]
I think that issue has something do with openai. Did you give it your api key? Did you try edit the prompt?

**Comment by MxDkl** [comment]
I'm confident it's an api key error. Don't put the api key between the <>.

**Comment by MxDkl** [comment]
Cool
